/* 
 * PassTicketException 
 * Version V1.00
 * 
 * Licensed Materials - Property of IBM
 * 5650-ZOS
 * Copyright IBM Corp. 2020, 2021
 * 
 * THIS CODE HAS NOT BEEN SUBMITTED TO ANY FORMAL IBM TEST
 * AND IS DISTRIBUTED ON AN "AS IS" BASIS WITHOUT ANY
 * WARRANTY EITHER EXPRESS OR IMPLIED. THE IMPLEMENTATION
 * OF ANY OF THE TECHNIQUES DESCRIBED OR USED HEREIN IS A
 * CUSTOMER RESPONSIBILITY AND DEPENDS ON THE CUSTOMER'S
 * OPERATIONAL ENVIRONMENT. WHILE EACH ITEM MAY HAVE BEEN
 * REVIEWED FOR ACCURACY IN A SPECIFIC SITUATION AND MAY
 * RUN IN A SPECIFIC ENVIRONMENT, THERE IS NO GUARANTEE
 * THAT THE SAME OR SIMILAR RESULTS WILL BE OBTAINED ELSE-
 * WHERE. CUSTOMERS ATTEMPTING TO ADAPT THESE TECHNIQUES TO
 * THEIR OWN ENVIRONMENTS DO SO AT THEIR OWN RISK.
 */
package com.ibm.eserver.PassTicket;

public class PassTicketException extends Exception {

  private static final long serialVersionUID = 1L;

  public PassTicketException(String message) {
    super(message);
  }
}
