# Property of IBM      
# Copyright IBM Corp. 2018
# All Rights Reserved.
#
# Title: Makefile 
#
# Purpose: Make the ifind utility
#
# Author: Anthony Giorgio <agiorgio@us.ibm.com>
#

.SUFFIX:

CC=c99
CFLAGS=-O2 -Wc,xplink,inline
LDFLAGS=-Wl,xplink,edit=no

all: ifind  

clean:
	rm -f *.o ifind 

